---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
```

```{r}
link='https://github.com/Bearnamedjoey/guided1/raw/main/Country%20Comparison.csv'
```


```{r}
myFile=url(link)
```

```{r}
fromPy=read_csv(file = myFile)
```
```{r}
row.names(fromPy)=NULL
```

```{r}
str(fromPy)
```
```{r}
dataToCluster=fromPy[,-c(1)]
```

```{r}
row.names(dataToCluster)=fromPy$Country
```
```{r}
set.seed(999)
```

```{r}
library(cluster)
distanceMatrix=daisy(x=dataToCluster, metric = "gower")
```

```{r}
projectedData = cmdscale(distanceMatrix, k=2)
```

```{r}
fromPy$dim1 = projectedData[,1]
fromPy$dim2 = projectedData[,2]
```

```{r}
library(ggplot2)
base= ggplot(data=fromPy,
             aes(x=dim1, y=dim2,
                 label=Country)) 
base + geom_text(size=2)
```
```{r}
hc = hclust(distanceMatrix)
```

```{r}
plot(hc,hang = -1,cex=0.5)
```
```{r}
library(factoextra)
```
```{r}
```



```{r}
fviz_nbclust(dataToCluster, 
             hcut,
             diss=distanceMatrix,
             method = "gap_stat",
             k.max = 10,
             verbose = F,
             hc_func = "agnes")
```

